# Site settings
title: A test of Jekyll in prep for CDS August institute - 3
description: All sorts of interesting things to be seen here.
theme: minima
# theme: jekyll-theme-minimal # You can change this to the desired theme
# remote_theme: pages-themes/merlot@v0.2.0

# Main nav for the minima theme

header_pages:
  - index.md
  - page1.md

# navigation:
#   - name: Home
#     link: ./index.html
#     sublist:
#       - name: Another page
#         link: ./page1.html
#   - name: Another Page (again)
#     link: ./page1.html
