# Site settings
title: A test of Jekyll in prep for CDS August institute
description: All sorts of interesting things to be seen here.
# theme: jekyll-theme-minimal # You can change this to the desired theme
remote_theme: pages-themes/merlot@v0.2.0
